#ifndef __LIB_UTIL_UNIX_PRIVS_H__
#define __LIB_UTIL_UNIX_PRIVS_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif

#ifndef _PURE_
#define _PURE_
#endif

#ifndef _NORETURN_
#define _NORETURN_
#endif

#ifndef _DEPRECATED_
#define _DEPRECATED_
#endif

#ifndef _WARN_UNUSED_RESULT_
#define _WARN_UNUSED_RESULT_
#endif


/* The following definitions come from lib/util/unix_privs.c  */


/**
 * Obtain root privileges for the current process.
 *
 * The privileges can be dropped by talloc_free()-ing the 
 * token returned by this function
 */
void *root_privileges(void);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __LIB_UTIL_UNIX_PRIVS_H__ */

